import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { GameStatus } from 'interfaces';

export class GameResponseSchema {
  @ApiPropertyOptional({
    description: "The game's UUID, read-only, generated by the server.",
    example: '3fa85f64-5717-4562-b3fc-2c963f66afa6',
  })
  id: string;

  @ApiProperty({
    description: 'The board state',
    example: 'XO--X--OX',
  })
  board: string;

  @ApiPropertyOptional({
    description: 'The game status',
    example: GameStatus.running,
  })
  status: GameStatus;
}
