import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { GameStatus } from 'interfaces';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

@Entity()
export class Game {
  @PrimaryGeneratedColumn('uuid')
  @ApiPropertyOptional({
    description: "The game's UUID, read-only, generated by the server.",
  })
  id: string;

  @Column({ length: 9 })
  @ApiProperty({ description: 'The board state' })
  board: string;

  @ApiPropertyOptional({
    description: 'The game status',
  })
  @Column({ type: 'enum', enum: GameStatus, default: GameStatus.running })
  status: GameStatus;
}
